# fly.toml app configuration file generated for the-stork-journal-a1 on 2024-07-04T00:19:10+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'the-stork-journal-a1'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
